#!/bin/bash
# Render /data/config/config.toml for the Docker deployment.
#
# This was entrypoint.sh's `if [ ! -f "$CONFIG_FILE" ]` block, lifted out so it
# can be run without a Nextcloud to provision against. The entrypoint still owns
# the decision of *whether* to render, and since ISSUE-368 the answer is "every
# boot" — this script is the single writer of config.toml, and the three
# add-if-missing backfill passes that used to repair an existing config on an
# upgrade are gone, because a fresh render supersedes all three.
#
# It is executed, never sourced. entrypoint.sh runs `set -euo pipefail`, so a
# sourced script would inherit `-u` and abort the entire boot on any unset
# variable it happened to read. As a subprocess, a bad hand-off fails the render
# and leaves the caller free to say so.
#
# INPUTS. These are not the environment in the ordinary sense — they are shell
# locals the provisioning phase produces earlier in entrypoint.sh, exported
# across the call. The ISTOTA_* variables are the operator-facing ones from
# docker-compose.yml and carry `:-` defaults; the rest come from provisioning:
#
# Line numbers are deliberately absent — they drift on the next edit to the
# entrypoint, and this header already went stale once that way. Each name below
# is greppable in entrypoint.sh, which does not.
#
#   CONFIG_FILE     required  where to write
#   USER_NAME       required  the primary user's id
#   NC_URL          required  internal Nextcloud URL (NC_INTERNAL_URL)
#   APP_PASSWORD    required  the bot's Nextcloud app password (from BOT_PASSWORD)
#   BOT_USER                  the bot's Nextcloud login (default "istota")
#   USER_DISPLAY_NAME, USER_TIMEZONE, USER_EMAIL
#   USER_LOG_CHANNEL, USER_ALERTS_CHANNEL, USER_DISABLED_SKILLS
#   USER_DISABLED_MODULES
#   USER_MAX_FOREGROUND_WORKERS, USER_MAX_BACKGROUND_WORKERS
#   LOG_TOKEN, ALERTS_TOKEN         room tokens, from create_group_room
#   LOCATION_INGEST_TOKEN           generated by the provisioning phase
#   OAUTH_CLIENT_ID, OAUTH_CLIENT_SECRET, OAUTH_REDIRECT_URI
#   WEB_PORT
#   WEB_SESSION_SECRET              the web session signing key, resolved once
#                                   per boot by entrypoint.sh so a re-render
#                                   keeps it; a fresh one is minted here when
#                                   no caller supplies it
#   MONARCH_EMAIL, MONARCH_PASSWORD
#   ISTOTA_*                        see docker/docker-compose.yml
#
# **No backticks inside a heredoc in this file.** Every heredoc here is
# unquoted so that ${...} expands, which is the point, and a backtick pair is
# therefore a command substitution rather than the prose markup a reader writing
# a comment intends: the shell runs the words between them, says "command not
# found" on stderr, substitutes the empty string, and the script exits 0 with
# the words gone from its own output. Measured on the [talk.signaling] block,
# whose comment named two files that way and rendered with both names missing.
# `tests/test_render_config.py::TestNoHeredocRunsACommand` refuses one, and the
# render helper there requires empty stderr for the same class of defect.
#
# `tests/test_render_config.py` holds entrypoint.sh's `export` list to this
# contract, so a name added here without being exported fails a test rather than
# rendering as empty on a real boot.
#
# Two of the provisioning locals the entrypoint holds are deliberately absent:
# ROOM_TOKEN and GENERAL_TOKEN are never read by the render.
#
# The body below is the extracted block, unchanged. It sits inside a function so
# it can keep its original indentation — the heredoc bodies it contains are at
# column 0, and dedenting the surrounding shell would have meant editing 460
# lines of interleaved heredocs to save four spaces.

set -euo pipefail

# Fail before writing anything, naming every missing input. Bare `set -u` would
# abort at the first unbound read instead, part-way through the file, leaving a
# truncated config that the entrypoint's own file-exists guard then treats as
# complete on the next boot.
#
# The test is "set", not "non-empty", so this is exactly the abort `set -u` gave
# before the extraction and no deployment that rendered a config yesterday stops
# rendering one today. An empty APP_PASSWORD still produces an empty
# `app_password`, as it always did.
#
# Written out four times rather than looped over ${!name+x}: macOS ships bash
# 3.2, this file's tests run there, and indirect expansion with an operator is
# not somewhere to discover a version difference.
missing=""
[ -n "${CONFIG_FILE+x}" ] || missing="$missing CONFIG_FILE"
[ -n "${USER_NAME+x}" ] || missing="$missing USER_NAME"
[ -n "${NC_URL+x}" ] || missing="$missing NC_URL"
[ -n "${APP_PASSWORD+x}" ] || missing="$missing APP_PASSWORD"
if [ -n "$missing" ]; then
    echo "[istota] render-config.sh: missing required input(s):$missing" >&2
    exit 2
fi

# Escape a value for a TOML basic string.
#
# Every credential below is interpolated into a `"`-delimited string by a shell
# heredoc, which does no escaping of its own. A `"` in an operator's password
# therefore closes the string early and the file stops being valid TOML — while
# the render still exits 0 and prints "Config written to", so the entrypoint's
# file-exists guard treats the corrupt file as complete on every later boot and
# never regenerates it. Found by review, reproduced, and covered by
# `tests/test_render_config.py::TestQuotingSurvivesTheRender`.
#
# Backslash first: escaping it after the quote would double the backslash the
# quote-escape just introduced.
toml_escape() {
    local value="$1"
    value="${value//\\/\\\\}"
    value="${value//\"/\\\"}"
    printf '%s' "$value"
}

# Render a comma-separated operator value as a TOML array of strings.
#
# `sed 's/[^,]*/"&"/g'` did this and got three things wrong, each of which
# reaches the daemon as a fact rather than as an error. A `"` in a value closed
# the string early and produced a config that does not parse — on a first boot
# there is no config.toml.prev to fall back to, so that is a crash loop. A space
# after a comma stayed part of the name, so ` briefings` matched no module and
# silently did nothing. A trailing comma produced an empty element.
#
# Split with `case` rather than by IFS word-splitting, which would also glob:
# the value is operator-written, but it is not this function's job to decide
# whether a `*` in it was meant.
#
# Prints nothing when every element is empty, so a caller's `-n` test on the
# raw value is not the only thing deciding whether the key gets written.
toml_string_list() {
    local rest="$1" item out=""
    while [ -n "$rest" ]; do
        case "$rest" in
            *,*) item="${rest%%,*}"; rest="${rest#*,}" ;;
            *)   item="$rest"; rest="" ;;
        esac
        item="${item#"${item%%[![:space:]]*}"}"
        item="${item%"${item##*[![:space:]]}"}"
        [ -n "$item" ] || continue
        [ -n "$out" ] && out="$out, "
        out="$out\"$(toml_escape "$item")\""
    done
    # `if` rather than a trailing `&&`: this is the function's last command, so
    # under the script's `set -e` an empty list would make `x="$(...)"` abort
    # the whole render rather than assign the empty string.
    if [ -n "$out" ]; then
        printf '[%s]' "$out"
    fi
}

# The five that can carry a metacharacter: four an operator types by hand into
# docker/.env, plus the mount point, which compose supplies but an operator may
# override and which is free text on the Nextcloud side (a display name, not a
# slug). Everything else rendered into a TOML string is machine-generated hex, a
# URL, or a value from the Nextcloud API.
#
# Rewritten in place rather than into new names so the extracted body below
# stays byte-identical to what it was in entrypoint.sh. Safe because this is a
# subprocess: the escaped values die with it and never reach the daemon.
APP_PASSWORD="$(toml_escape "${APP_PASSWORD}")"
ISTOTA_EMAIL_IMAP_PASSWORD="$(toml_escape "${ISTOTA_EMAIL_IMAP_PASSWORD:-}")"
ISTOTA_DEVELOPER_GITLAB_TOKEN="$(toml_escape "${ISTOTA_DEVELOPER_GITLAB_TOKEN:-}")"
ISTOTA_DEVELOPER_GITHUB_TOKEN="$(toml_escape "${ISTOTA_DEVELOPER_GITHUB_TOKEN:-}")"
ISTOTA_NEXTCLOUD_DAV_PREFIX="$(toml_escape "${ISTOTA_NEXTCLOUD_DAV_PREFIX:-}")"

render_config() {
    echo "[istota] Generating config.toml..."

    DISPLAY_NAME="${USER_DISPLAY_NAME:-$USER_NAME}"
    TIMEZONE="${USER_TIMEZONE:-UTC}"

    cat > "$CONFIG_FILE" <<TOML
# Istota configuration — generated by Docker entrypoint

bot_name = "${ISTOTA_BOT_NAME:-Istota}"
emissaries_enabled = ${ISTOTA_EMISSARIES_ENABLED:-true}

db_path = "/data/db/istota.db"
nextcloud_mount_path = "/mnt/shared"
skills_dir = "/app/config/skills"
temp_dir = "/data/tmp"
max_memory_chars = ${ISTOTA_MAX_MEMORY_CHARS:-0}
TOML

    # No top-level `model` key any more. It was the claude_code brain's own
    # default living at the root, where the executor applied it to whatever
    # brain ran and it shadowed that brain's configured default (ISSUE-418).
    # ISTOTA_MODEL still works and is migrated onto the per-brain keys by the
    # [brain.claude_code] / [brain.tmux] render below — done here rather than by
    # the loader's deprecation path so a Docker deployment that never changes
    # its .env stops warning at every boot. The generator is what a generated
    # config is for.

    # Disabled skills (optional). Through `toml_string_list` like every other
    # comma-separated value here: this one is deployment-wide, so a `"` in it
    # breaks the whole config rather than one user's key.
    _disabled_skills_list="$(toml_string_list "${ISTOTA_DISABLED_SKILLS:-}")"
    if [ -n "$_disabled_skills_list" ]; then
        echo "disabled_skills = $_disabled_skills_list" >> "$CONFIG_FILE"
    fi

    # Experimental features (operator opt-in for rough, off-by-default work).
    # Comma-separated, e.g. "money_tax,money_wash_sales". See docs/EXPERIMENTAL.md.
    cat >> "$CONFIG_FILE" <<TOML

[experimental]
TOML
    _experimental_list="$(toml_string_list "${ISTOTA_EXPERIMENTAL_FEATURES:-}")"
    if [ -n "$_experimental_list" ]; then
        echo "features = $_experimental_list" >> "$CONFIG_FILE"
    else
        echo "features = []" >> "$CONFIG_FILE"
    fi

    # Brain (model backend). kind=claude_code (default) shells out to the
    # Claude CLI; kind=native runs the in-process agent loop; kind=tmux_claude
    # drives the interactive TUI via tmux. The native provider API key is read
    # from ISTOTA_BRAIN_NATIVE_API_KEY at load time, so it is deliberately not
    # written into config.toml.
    #
    # Brain fallback (availability failover): when the primary brain is
    # unavailable (usage limit / missing binary / tmux launch failure), rerun the
    # task on ISTOTA_BRAIN_FALLBACK with that brain's own settings. "" = none,
    # whatever the primary kind (ISSUE-362) — except that an unset value on a
    # tmux_claude primary is filled in with claude_code below.
    cat >> "$CONFIG_FILE" <<TOML

[brain]
kind = "${ISTOTA_BRAIN_KIND:-claude_code}"
fallback_on_transient = ${ISTOTA_BRAIN_FALLBACK_ON_TRANSIENT:-false}
fallback_cooldown_seconds = ${ISTOTA_BRAIN_FALLBACK_COOLDOWN_SECONDS:-900}
TOML
    # Which brain kinds a room may pin for itself, and which a scheduled job may
    # pin with `brain` in CRON.md -- one list bounds every pin written outside
    # this file, so the key's name is narrower than the setting. Comma-separated,
    # empty by default, so both are off until an operator names kinds.
    # Rendered only when at least one name survives: an empty list and an absent
    # key load identically, and this file is rewritten on every boot, so a key
    # printed at its own default invites editing a generated file.
    #
    # Each name goes through `toml_escape`, for the reason every operator-typed
    # value here does -- a `"` would otherwise close the string early and leave a
    # config.toml that does not parse, which on this shape is a container that
    # will not boot. Nothing here judges whether a name is a real brain kind:
    # `config._validate_room_selectable` warns once at load about a name
    # `make_brain` cannot build, and a second opinion in a shell script would
    # only go out of date when a fourth kind ships.
    #
    # Every branch is an explicit `if`. `set -e` is in force, and the idiomatic
    # `[ -z "$x" ] && continue` exits the whole render whenever the test is
    # false -- which is the ordinary case, so it would fail every boot that set
    # this variable.
    if [ -n "${ISTOTA_BRAIN_ROOM_SELECTABLE:-}" ]; then
        _room_selectable=""
        _IFS_SAVED="$IFS"
        IFS=','
        for _kind in $ISTOTA_BRAIN_ROOM_SELECTABLE; do
            _kind="$(echo "$_kind" | tr -d '[:space:]')"
            if [ -z "$_kind" ]; then
                continue
            fi
            if [ -n "$_room_selectable" ]; then
                _room_selectable="${_room_selectable}, "
            fi
            _room_selectable="${_room_selectable}\"$(toml_escape "$_kind")\""
        done
        IFS="$_IFS_SAVED"
        if [ -n "$_room_selectable" ]; then
            echo "room_selectable = [${_room_selectable}]" >> "$CONFIG_FILE"
        fi
    fi

    # A tmux_claude primary with nothing set gets claude_code written in, which
    # is the failover it had implicitly before ISSUE-362 — same default the
    # Ansible role applies, so the two deployment shapes agree. Setting
    # ISTOTA_BRAIN_FALLBACK to any other value, including a single space, wins.
    # Since ISSUE-368 this reaches every boot rather than the first alone, so a
    # tmux deployment provisioned before ISSUE-362 gets the key on its next
    # restart instead of only learning from the config-load INFO line that it
    # has no failover.
    _brain_fallback="${ISTOTA_BRAIN_FALLBACK:-}"
    if [ -z "$_brain_fallback" ] \
        && [ "${ISTOTA_BRAIN_KIND:-claude_code}" = "tmux_claude" ]; then
        _brain_fallback="claude_code"
    fi
    if [ -n "$_brain_fallback" ]; then
        echo "fallback = \"${_brain_fallback}\"" >> "$CONFIG_FILE"
    fi

    # Each CLI brain's own default model / effort (ISSUE-418). Both blocks are
    # rendered whatever `kind` is, unlike [brain.native] below, because both are
    # read whatever it is: a native primary with a claude_code fallback, or a
    # source_type_overrides entry, runs the other brain and needs its default.
    #
    # ISTOTA_MODEL is the legacy spelling and feeds both, which is what makes
    # the migration exactly behaviour-preserving: it *was* the default for
    # whichever CLI brain ran, and the two share the anthropic namespace and the
    # same binary, so the value is equally valid in either. It is deliberately
    # not fed to [brain.native] — a value written in the Anthropic vocabulary
    # cannot carry to an openai_compat endpoint, which is the defect itself.
    #
    # A section header is written only when the block has a key to hold, so an
    # unconfigured deployment renders neither and loads the dataclass defaults.
    _cc_model="${ISTOTA_BRAIN_CLAUDE_CODE_MODEL:-${ISTOTA_MODEL:-}}"
    _cc_effort="${ISTOTA_BRAIN_CLAUDE_CODE_EFFORT:-}"
    if [ -n "$_cc_model" ] || [ -n "$_cc_effort" ]; then
        echo "" >> "$CONFIG_FILE"
        echo "[brain.claude_code]" >> "$CONFIG_FILE"
        if [ -n "$_cc_model" ]; then
            echo "model = \"$(toml_escape "$_cc_model")\"" >> "$CONFIG_FILE"
        fi
        if [ -n "$_cc_effort" ]; then
            echo "effort = \"$(toml_escape "$_cc_effort")\"" >> "$CONFIG_FILE"
        fi
    fi
    # [brain.tmux]'s own model/effort are emitted with the rest of that block
    # further down, not here: this file already writes a `[brain.tmux]` header
    # for the tmux kind, and a second one is a duplicate table — invalid TOML,
    # which on this shape is a container that will not boot.
    if [ "${ISTOTA_BRAIN_KIND:-claude_code}" = "native" ]; then
        cat >> "$CONFIG_FILE" <<TOML

[brain.native]
provider = "${ISTOTA_BRAIN_NATIVE_PROVIDER:-openai_compat}"
base_url = "${ISTOTA_BRAIN_NATIVE_BASE_URL:-https://api.anthropic.com/v1}"
context_window = ${ISTOTA_BRAIN_NATIVE_CONTEXT_WINDOW:-0}
max_turns = ${ISTOTA_BRAIN_NATIVE_MAX_TURNS:-100}
max_tokens = ${ISTOTA_BRAIN_NATIVE_MAX_TOKENS:-16384}
TOML
        # Scalar [brain.native] keys (effort, model, prompt_caching) must
        # precede the [brain.native.web_fetch] subtable and the [models.roles]
        # table below, or TOML would attach them to the wrong table.
        #
        # prompt_caching is tri-state and the empty value is *not* false: the
        # dataclass default is None, which llm/__init__.py reads as "on for
        # api.anthropic.com, off elsewhere". So the key is omitted unless the
        # operator forced one, the way the Ansible template already does it —
        # rendering `false` unconditionally, which this file did until
        # ISSUE-430, turned caching off on the default Anthropic deployment and
        # paid full uncached input every turn. Anything that is not true/false
        # is dropped rather than written, since a bare word here is invalid
        # TOML and on this shape that is a container that will not boot.
        case "$(printf '%s' "${ISTOTA_BRAIN_NATIVE_PROMPT_CACHING:-}" | tr '[:upper:]' '[:lower:]')" in
            true)  echo "prompt_caching = true" >> "$CONFIG_FILE" ;;
            false) echo "prompt_caching = false" >> "$CONFIG_FILE" ;;
            "")    : ;;
            *)     echo "[istota] WARNING: ignoring ISTOTA_BRAIN_NATIVE_PROMPT_CACHING (expected true or false)" >&2 ;;
        esac
        if [ -n "${ISTOTA_BRAIN_NATIVE_EFFORT:-}" ]; then
            echo "effort = \"${ISTOTA_BRAIN_NATIVE_EFFORT}\"" >> "$CONFIG_FILE"
        fi
        if [ -n "${ISTOTA_BRAIN_NATIVE_MODEL:-}" ]; then
            echo "model = \"${ISTOTA_BRAIN_NATIVE_MODEL}\"" >> "$CONFIG_FILE"
        fi
        # Daemon-side WebFetch tool (native-only, SSRF-hardened). Safe defaults;
        # only enabled / allow_http commonly change.
        cat >> "$CONFIG_FILE" <<TOML

[brain.native.web_fetch]
enabled = ${ISTOTA_BRAIN_NATIVE_WEB_FETCH_ENABLED:-true}
allow_http = ${ISTOTA_BRAIN_NATIVE_WEB_FETCH_ALLOW_HTTP:-false}
require_url_provenance = ${ISTOTA_BRAIN_NATIVE_WEB_FETCH_REQUIRE_URL_PROVENANCE:-false}
TOML
        if [ -n "${ISTOTA_BRAIN_NATIVE_MODEL:-}" ]; then
            # Internal subsystems (conversation selection, sleep-cycle
            # extraction, OCR, …) request models by ROLE — "fast" / "general" /
            # "smart". The claude_code brain maps those to Haiku/Sonnet/Opus.
            # A native brain speaks to one endpoint, so an unmapped role
            # already falls back to the single configured model; what this
            # table buys is pointing one role somewhere else. Set
            # ISTOTA_BRAIN_NATIVE_MODEL_{FAST,GENERAL,SMART} to aim a role at a
            # different model served by the same endpoint.
            #
            # The key is [models.aliases]. [models.roles] is a hard rename that
            # config.py parses into nothing — writing it dropped every override
            # here and logged a migration warning on every process start.
            cat >> "$CONFIG_FILE" <<TOML

[models.aliases]
fast = "${ISTOTA_BRAIN_NATIVE_MODEL_FAST:-$ISTOTA_BRAIN_NATIVE_MODEL}"
general = "${ISTOTA_BRAIN_NATIVE_MODEL_GENERAL:-$ISTOTA_BRAIN_NATIVE_MODEL}"
smart = "${ISTOTA_BRAIN_NATIVE_MODEL_SMART:-$ISTOTA_BRAIN_NATIVE_MODEL}"
TOML
        fi
    fi

    # Tmux-driven interactive-TUI brain (subscription billing). The operability
    # knobs are emitted only when the kind is selected; all of them default in
    # code to the prototype's pinned values.
    #
    # The block itself is also emitted when only this brain's own model/effort
    # are set (ISSUE-418), because those are read whatever `kind` is — a
    # claude_code primary with a tmux fallback, or a source_type_overrides entry,
    # runs this brain and needs its default. One header either way: this file
    # writes `[brain.tmux]` exactly once, since a duplicate table is invalid TOML
    # and on this shape that is a container that will not boot.
    _tmux_model="${ISTOTA_BRAIN_TMUX_MODEL:-${ISTOTA_MODEL:-}}"
    _tmux_effort="${ISTOTA_BRAIN_TMUX_EFFORT:-}"
    if [ "${ISTOTA_BRAIN_KIND:-claude_code}" = "tmux_claude" ] \
        || [ -n "$_tmux_model" ] || [ -n "$_tmux_effort" ]; then
        echo "" >> "$CONFIG_FILE"
        echo "[brain.tmux]" >> "$CONFIG_FILE"
        if [ -n "$_tmux_model" ]; then
            echo "model = \"$(toml_escape "$_tmux_model")\"" >> "$CONFIG_FILE"
        fi
        if [ -n "$_tmux_effort" ]; then
            echo "effort = \"$(toml_escape "$_tmux_effort")\"" >> "$CONFIG_FILE"
        fi
    fi
    if [ "${ISTOTA_BRAIN_KIND:-claude_code}" = "tmux_claude" ]; then
        cat >> "$CONFIG_FILE" <<TOML
fallback_trip_threshold = ${ISTOTA_BRAIN_TMUX_FALLBACK_TRIP_THRESHOLD:-5}
fallback_cooldown_seconds = ${ISTOTA_BRAIN_TMUX_FALLBACK_COOLDOWN_SECONDS:-300}
ready_timeout_seconds = ${ISTOTA_BRAIN_TMUX_READY_TIMEOUT_SECONDS:-30}
cli_version_pin = "${ISTOTA_BRAIN_TMUX_CLI_VERSION_PIN:-2.1.168}"
TOML
    fi

    cat >> "$CONFIG_FILE" <<TOML

[security]
sandbox_enabled = ${ISTOTA_SECURITY_SANDBOX_ENABLED:-true}
skill_proxy_enabled = ${ISTOTA_SECURITY_SKILL_PROXY_ENABLED:-true}
skill_proxy_timeout = ${ISTOTA_SECURITY_SKILL_PROXY_TIMEOUT:-300}
sandbox_cache_dir = "${ISTOTA_SECURITY_SANDBOX_CACHE_DIR:-}"

[security.network]
enabled = false

[nextcloud]
url = "${NC_URL}"
username = "${BOT_USER:-istota}"
app_password = "${APP_PASSWORD}"
# Where /mnt/shared sits inside the bot's own Nextcloud file tree. On this shape
# it is a files_external mount, so a logical /Users/x is /<mount>/Users/x over
# DAV and OCS; compose passes the mount point provision-nc.sh created. Empty is
# the bare-metal shape, where the rclone mount *is* the bot's tree.
dav_prefix = "${ISTOTA_NEXTCLOUD_DAV_PREFIX:-}"
# The boot-time OCS share of the bot workspace back to the user. Off on this
# shape: provision-nc.sh already mounts that directory into the user's tree, so
# the share would hand them a second copy of it.
auto_share_bot_dir = ${ISTOTA_NEXTCLOUD_AUTO_SHARE_BOT_DIR:-true}

[talk]
enabled = ${ISTOTA_TALK_ENABLED:-true}
bot_username = "${BOT_USER:-istota}"

# Inbound Talk over the standalone signaling server (the "high-performance
# backend"). Off unless the operator runs one: docker-compose.yml ships the
# container behind the signaling compose profile, and a deployment without it
# keeps the poll loop, which is the capability floor rather than a fallback.
#
# There is no credential here, and the absence is the design. istota
# authenticates to the signaling server as its own Nextcloud user, so the HPB
# URL, the hello token and the per-room Talk session id are all minted on demand
# by Talk. The protocol's other door — an internal client holding the server's
# shared secret — joins any room on the instance and is rejected for that
# reason, so there is nothing to render, redact or vault.
#
# An empty url means "read the server address from Talk's own signaling
# settings". Set it where the daemon must reach the HPB by a different route
# than the one Nextcloud advertises to browsers — which is exactly the shape of
# a compose deployment, where Talk hands out the public URL and the daemon is on
# the container network beside the server.
[talk.signaling]
enabled = ${ISTOTA_TALK_SIGNALING_ENABLED:-false}
url = "${ISTOTA_TALK_SIGNALING_URL:-}"
room_sync_interval = ${ISTOTA_TALK_SIGNALING_ROOM_SYNC_INTERVAL:-300}
reconnect_backoff_max = ${ISTOTA_TALK_SIGNALING_RECONNECT_BACKOFF_MAX:-60}
payload_direct = ${ISTOTA_TALK_SIGNALING_PAYLOAD_DIRECT:-false}

[email]
enabled = ${ISTOTA_EMAIL_ENABLED:-false}
TOML

    if [ "${ISTOTA_EMAIL_ENABLED:-false}" = "true" ]; then
        cat >> "$CONFIG_FILE" <<TOML
imap_host = "${ISTOTA_EMAIL_IMAP_HOST:-}"
imap_port = ${ISTOTA_EMAIL_IMAP_PORT:-993}
imap_user = "${ISTOTA_EMAIL_IMAP_USER:-}"
imap_password = "${ISTOTA_EMAIL_IMAP_PASSWORD:-}"
smtp_host = "${ISTOTA_EMAIL_SMTP_HOST:-}"
smtp_port = ${ISTOTA_EMAIL_SMTP_PORT:-587}
poll_folder = "${ISTOTA_EMAIL_POLL_FOLDER:-INBOX}"
bot_email = "${ISTOTA_EMAIL_BOT_ADDRESS:-}"
authserv_id = "${ISTOTA_EMAIL_AUTHSERV_ID:-}"
confirm_sender_match = "${ISTOTA_EMAIL_CONFIRM_SENDER_MATCH:-off}"
outbound_approval_floor = "${ISTOTA_EMAIL_OUTBOUND_APPROVAL_FLOOR:-untrusted}"
TOML
    fi

    cat >> "$CONFIG_FILE" <<TOML

[conversation]
enabled = ${ISTOTA_CONVERSATION_ENABLED:-true}
lookback_count = ${ISTOTA_CONVERSATION_LOOKBACK_COUNT:-25}
selection_model = "${ISTOTA_CONVERSATION_SELECTION_MODEL:-fast}"
selection_timeout = ${ISTOTA_CONVERSATION_SELECTION_TIMEOUT:-30.0}
skip_selection_threshold = ${ISTOTA_CONVERSATION_SKIP_SELECTION_THRESHOLD:-3}
use_selection = ${ISTOTA_CONVERSATION_USE_SELECTION:-true}
always_include_recent = ${ISTOTA_CONVERSATION_ALWAYS_INCLUDE_RECENT:-5}
context_truncation = ${ISTOTA_CONVERSATION_CONTEXT_TRUNCATION:-0}
context_recency_hours = ${ISTOTA_CONVERSATION_CONTEXT_RECENCY_HOURS:-0}
context_min_messages = ${ISTOTA_CONVERSATION_CONTEXT_MIN_MESSAGES:-10}
previous_tasks_count = ${ISTOTA_CONVERSATION_PREVIOUS_TASKS_COUNT:-3}
talk_context_limit = ${ISTOTA_CONVERSATION_TALK_CONTEXT_LIMIT:-100}

[logging]
level = "${ISTOTA_LOGGING_LEVEL:-INFO}"
output = "${ISTOTA_LOGGING_OUTPUT:-console}"
file = "${ISTOTA_LOGGING_FILE:-}"
rotate = ${ISTOTA_LOGGING_ROTATE:-true}
max_size_mb = ${ISTOTA_LOGGING_MAX_SIZE_MB:-10}
backup_count = ${ISTOTA_LOGGING_BACKUP_COUNT:-5}

[scheduler]
poll_interval = ${ISTOTA_SCHEDULER_POLL_INTERVAL:-5}
dispatch_interval = ${ISTOTA_SCHEDULER_DISPATCH_INTERVAL:-0.5}
talk_poll_interval = ${ISTOTA_SCHEDULER_TALK_POLL_INTERVAL:-10}
talk_poll_timeout = ${ISTOTA_SCHEDULER_TALK_POLL_TIMEOUT:-30}
talk_poll_wait = ${ISTOTA_SCHEDULER_TALK_POLL_WAIT:-2.0}
talk_poll_full_sweep_interval = ${ISTOTA_SCHEDULER_TALK_POLL_FULL_SWEEP_INTERVAL:-300}
email_poll_interval = ${ISTOTA_SCHEDULER_EMAIL_POLL_INTERVAL:-60}
briefing_check_interval = ${ISTOTA_SCHEDULER_BRIEFING_CHECK_INTERVAL:-60}
tasks_file_poll_interval = ${ISTOTA_SCHEDULER_TASKS_FILE_POLL_INTERVAL:-30}
shared_file_check_interval = ${ISTOTA_SCHEDULER_SHARED_FILE_CHECK_INTERVAL:-120}
heartbeat_check_interval = ${ISTOTA_SCHEDULER_HEARTBEAT_CHECK_INTERVAL:-60}
progress_updates = ${ISTOTA_SCHEDULER_PROGRESS_UPDATES:-true}
progress_show_tool_use = ${ISTOTA_SCHEDULER_PROGRESS_SHOW_TOOL_USE:-true}
progress_show_text = ${ISTOTA_SCHEDULER_PROGRESS_SHOW_TEXT:-false}
event_log_enabled = ${ISTOTA_SCHEDULER_EVENT_LOG_ENABLED:-true}
stream_text_gate_chars = ${ISTOTA_SCHEDULER_STREAM_TEXT_GATE_CHARS:-280}
push_notification_threshold_seconds = ${ISTOTA_SCHEDULER_PUSH_NOTIFICATION_THRESHOLD_SECONDS:-30}
push_notification_sources = ${ISTOTA_SCHEDULER_PUSH_NOTIFICATION_SOURCES:-[]}
log_channel_show_skills = ${ISTOTA_SCHEDULER_LOG_CHANNEL_SHOW_SKILLS:-true}
task_timeout_minutes = ${ISTOTA_SCHEDULER_TASK_TIMEOUT_MINUTES:-30}
confirmation_timeout_minutes = ${ISTOTA_SCHEDULER_CONFIRMATION_TIMEOUT_MINUTES:-120}
stale_pending_warn_minutes = ${ISTOTA_SCHEDULER_STALE_PENDING_WARN_MINUTES:-30}
stale_pending_fail_hours = ${ISTOTA_SCHEDULER_STALE_PENDING_FAIL_HOURS:-2}
max_retry_age_minutes = ${ISTOTA_SCHEDULER_MAX_RETRY_AGE_MINUTES:-60}
worker_heartbeat_seconds = ${ISTOTA_SCHEDULER_WORKER_HEARTBEAT_SECONDS:-60}
worker_stuck_minutes = ${ISTOTA_SCHEDULER_WORKER_STUCK_MINUTES:-10}
task_retention_days = ${ISTOTA_SCHEDULER_TASK_RETENTION_DAYS:-7}
email_retention_days = ${ISTOTA_SCHEDULER_EMAIL_RETENTION_DAYS:-7}
worker_idle_timeout = ${ISTOTA_SCHEDULER_WORKER_IDLE_TIMEOUT:-10}
worker_idle_poll_interval = ${ISTOTA_SCHEDULER_WORKER_IDLE_POLL_INTERVAL:-0.5}
# 3/2 rather than config.py's 5/3, deliberately: the image is sized smaller
# than a bare-metal host. The two above are *not* per-shape — they match the
# dataclass, and worker_idle_timeout is 10 rather than the 30 this file carried
# until ISSUE-430 because e354c1e7 made the setting live (it had lingered one
# poll interval whatever the number said) and lowered the default with it.
max_foreground_workers = ${ISTOTA_SCHEDULER_MAX_FOREGROUND_WORKERS:-3}
max_background_workers = ${ISTOTA_SCHEDULER_MAX_BACKGROUND_WORKERS:-2}
user_max_foreground_workers = ${ISTOTA_SCHEDULER_USER_MAX_FOREGROUND_WORKERS:-2}
user_max_background_workers = ${ISTOTA_SCHEDULER_USER_MAX_BACKGROUND_WORKERS:-1}
scheduled_job_max_consecutive_failures = ${ISTOTA_SCHEDULER_SCHEDULED_JOB_MAX_CONSECUTIVE_FAILURES:-5}
cron_max_staleness_minutes = ${ISTOTA_SCHEDULER_CRON_MAX_STALENESS_MINUTES:-60}
max_subtasks_per_task = ${ISTOTA_SCHEDULER_MAX_SUBTASKS_PER_TASK:-10}
max_subtask_depth = ${ISTOTA_SCHEDULER_MAX_SUBTASK_DEPTH:-3}
max_subtask_prompt_chars = ${ISTOTA_SCHEDULER_MAX_SUBTASK_PROMPT_CHARS:-8000}
talk_cache_max_per_conversation = ${ISTOTA_SCHEDULER_TALK_CACHE_MAX_PER_CONVERSATION:-200}
temp_file_retention_days = ${ISTOTA_SCHEDULER_TEMP_FILE_RETENTION_DAYS:-7}
location_ping_retention_days = ${ISTOTA_SCHEDULER_LOCATION_PING_RETENTION_DAYS:-365}
db_health_check_interval = ${ISTOTA_SCHEDULER_DB_HEALTH_CHECK_INTERVAL:-86400}
main_loop_read_timeout_ms = ${ISTOTA_SCHEDULER_MAIN_LOOP_READ_TIMEOUT_MS:-2000}
scheduler_stats_interval = ${ISTOTA_SCHEDULER_STATS_INTERVAL:-60}
db_backup_enabled = ${ISTOTA_SCHEDULER_DB_BACKUP_ENABLED:-true}
db_backup_interval = ${ISTOTA_SCHEDULER_DB_BACKUP_INTERVAL:-86400}
db_backup_dir = "${ISTOTA_SCHEDULER_DB_BACKUP_DIR:-}"
db_backup_retention = ${ISTOTA_SCHEDULER_DB_BACKUP_RETENTION:-7}

[sleep_cycle]
enabled = ${ISTOTA_SLEEP_CYCLE_ENABLED:-true}
cron = "${ISTOTA_SLEEP_CYCLE_CRON:-0 2 * * *}"
lookback_hours = ${ISTOTA_SLEEP_CYCLE_LOOKBACK_HOURS:-24}
memory_retention_days = ${ISTOTA_SLEEP_CYCLE_MEMORY_RETENTION_DAYS:-0}
auto_load_dated_days = ${ISTOTA_SLEEP_CYCLE_AUTO_LOAD_DATED_DAYS:-3}
curate_user_memory = ${ISTOTA_SLEEP_CYCLE_CURATE_USER_MEMORY:-false}
curation_log_summary = ${ISTOTA_SLEEP_CYCLE_CURATION_LOG_SUMMARY:-true}
knowledge_graph_audit_retention_days = ${ISTOTA_SLEEP_CYCLE_KG_AUDIT_RETENTION_DAYS:-365}

[channel_sleep_cycle]
enabled = ${ISTOTA_CHANNEL_SLEEP_CYCLE_ENABLED:-true}
cron = "${ISTOTA_CHANNEL_SLEEP_CYCLE_CRON:-0 3 * * *}"
lookback_hours = ${ISTOTA_CHANNEL_SLEEP_CYCLE_LOOKBACK_HOURS:-24}
memory_retention_days = ${ISTOTA_CHANNEL_SLEEP_CYCLE_MEMORY_RETENTION_DAYS:-0}

[memory_search]
enabled = ${ISTOTA_MEMORY_SEARCH_ENABLED:-false}
TOML

    if [ "${ISTOTA_MEMORY_SEARCH_ENABLED:-false}" = "true" ]; then
        cat >> "$CONFIG_FILE" <<TOML
auto_index_conversations = ${ISTOTA_MEMORY_SEARCH_AUTO_INDEX_CONVERSATIONS:-true}
auto_index_memory_files = ${ISTOTA_MEMORY_SEARCH_AUTO_INDEX_MEMORY_FILES:-true}
auto_recall = ${ISTOTA_MEMORY_SEARCH_AUTO_RECALL:-false}
auto_recall_limit = ${ISTOTA_MEMORY_SEARCH_AUTO_RECALL_LIMIT:-5}
recency_half_life_days = ${ISTOTA_MEMORY_SEARCH_RECENCY_HALF_LIFE_DAYS:-180}
TOML
    fi

    # Learned playbooks (procedural memory) — off by default. Distilled by the
    # sleep cycle from successful multi-step tasks, recalled by relevance.
    if [ "${ISTOTA_PLAYBOOKS_ENABLED:-false}" = "true" ]; then
        cat >> "$CONFIG_FILE" <<TOML

[playbooks]
enabled = true
recall_limit = ${ISTOTA_PLAYBOOKS_RECALL_LIMIT:-3}
min_tool_calls = ${ISTOTA_PLAYBOOKS_MIN_TOOL_CALLS:-4}
retention_days = ${ISTOTA_PLAYBOOKS_RETENTION_DAYS:-90}
TOML
    fi

    # ntfy push notifications are configured per-user via the web settings UI
    # (`/istota/settings`). No operator-shared block is written.

    # Browser (optional)
    if [ "${ISTOTA_BROWSER_ENABLED:-false}" = "true" ]; then
        cat >> "$CONFIG_FILE" <<TOML

[browser]
enabled = true
api_url = "${ISTOTA_BROWSER_API_URL:-http://istota-browser:9223}"
vnc_url = "${ISTOTA_BROWSER_VNC_URL:-}"
TOML
    fi

    # Location tracking (optional)
    if [ "${ISTOTA_LOCATION_ENABLED:-false}" = "true" ]; then
        cat >> "$CONFIG_FILE" <<TOML

[location]
enabled = true
webhooks_port = ${ISTOTA_WEBHOOKS_PORT:-8765}
TOML
    fi

    # Developer skill (optional)
    if [ "${ISTOTA_DEVELOPER_ENABLED:-false}" = "true" ]; then
        cat >> "$CONFIG_FILE" <<TOML

[developer]
enabled = true
repos_dir = "${ISTOTA_DEVELOPER_REPOS_DIR:-}"
gitlab_url = "${ISTOTA_DEVELOPER_GITLAB_URL:-https://gitlab.com}"
gitlab_token = "${ISTOTA_DEVELOPER_GITLAB_TOKEN:-}"
gitlab_username = "${ISTOTA_DEVELOPER_GITLAB_USERNAME:-}"
gitlab_default_namespace = "${ISTOTA_DEVELOPER_GITLAB_DEFAULT_NAMESPACE:-}"
gitlab_reviewer = "${ISTOTA_DEVELOPER_GITLAB_REVIEWER:-}"
gitlab_reviewer_id = "${ISTOTA_DEVELOPER_GITLAB_REVIEWER_ID:-}"
github_url = "${ISTOTA_DEVELOPER_GITHUB_URL:-https://github.com}"
github_token = "${ISTOTA_DEVELOPER_GITHUB_TOKEN:-}"
github_username = "${ISTOTA_DEVELOPER_GITHUB_USERNAME:-}"
github_default_owner = "${ISTOTA_DEVELOPER_GITHUB_DEFAULT_OWNER:-}"
github_reviewer = "${ISTOTA_DEVELOPER_GITHUB_REVIEWER:-}"
gh_bin_path = "${ISTOTA_DEVELOPER_GH_BIN_PATH:-/usr/local/lib/istota_forge/gh}"
glab_bin_path = "${ISTOTA_DEVELOPER_GLAB_BIN_PATH:-/usr/local/lib/istota_forge/glab}"
TOML
        if [ -n "${ISTOTA_DEVELOPER_AUTHOR_CREDIT:-}" ]; then
            echo "author_credit = \"${ISTOTA_DEVELOPER_AUTHOR_CREDIT}\"" >> "$CONFIG_FILE"
        fi
    fi

    # Briefing defaults (optional)
    if [ -n "${ISTOTA_BRIEFING_DEFAULTS_NEWS_LOOKBACK_HOURS:-}" ] || [ -n "${ISTOTA_BRIEFING_DEFAULTS_NEWS_SOURCES:-}" ]; then
        echo "" >> "$CONFIG_FILE"
        echo "[briefing_defaults]" >> "$CONFIG_FILE"
        echo "[briefing_defaults.news]" >> "$CONFIG_FILE"
        echo "lookback_hours = ${ISTOTA_BRIEFING_DEFAULTS_NEWS_LOOKBACK_HOURS:-12}" >> "$CONFIG_FILE"
    fi

    # Web UI (auto-configured when provision-nc.sh registered an OAuth2 client).
    # OAUTH_CLIENT_ID / OAUTH_CLIENT_SECRET / OAUTH_REDIRECT_URI come from the
    # provisioning flag we sourced earlier.
    if [ -n "${OAUTH_CLIENT_ID:-}" ] && [ -n "${OAUTH_CLIENT_SECRET:-}" ]; then
        # NC user-facing URL — what the browser uses to authorize. Compose
        # defaults this to the nginx-proxied public URL; bare-metal can pin it
        # via ISTOTA_WEB_NC_EXTERNAL_URL. NC_URL (internal) is the last resort.
        WEB_NC_EXTERNAL_URL="${ISTOTA_WEB_NC_EXTERNAL_URL:-${NC_URL}}"
        # Supplied by the caller where there is one to keep. entrypoint.sh
        # resolves it once per boot (operator value, then the persisted file,
        # then the existing config, then fresh) precisely so re-rendering does
        # not mint a new key and drop every logged-in session. Minting one here
        # is the standalone path: the image tier and the lean compose stack call
        # this script with no entrypoint in front of it.
        WEB_SESSION_SECRET="${WEB_SESSION_SECRET:-$(python3 -c "import secrets; print(secrets.token_hex(32))")}"
        # Site hostname feeds web_app's external-origin / cookie scoping.
        # Defaults to the public host (proxied via nginx); falls back to the
        # web service's own port for bypass-nginx setups.
        WEB_SITE_HOSTNAME="${ISTOTA_WEB_SITE_HOSTNAME:-localhost:${WEB_PORT:-8766}}"
        # Redirect URI: prefer the value provision-nc.sh registered with NC
        # (sourced from $API_PROVISION_FLAG / $PROVISION_FLAG). Fall back to
        # ISTOTA_WEB_CALLBACK_URL (set by compose to the proxied path) so we
        # never write a stale default into config when the flag predates the
        # OAuth2 fields.
        WEB_REDIRECT_URI="${OAUTH_REDIRECT_URI:-${ISTOTA_WEB_CALLBACK_URL:-http://localhost:${WEB_PORT:-8766}/istota/callback}}"

        cat >> "$CONFIG_FILE" <<TOML

[web]
enabled = true
port = ${WEB_PORT:-8766}
oauth2_provider = "${WEB_NC_EXTERNAL_URL}"
oauth2_client_id = "${OAUTH_CLIENT_ID}"
oauth2_client_secret = "${OAUTH_CLIENT_SECRET}"
oauth2_token_endpoint = "${NC_URL}/index.php/apps/oauth2/api/v1/token"
oauth2_userinfo_endpoint = "${NC_URL}/ocs/v2.php/cloud/user?format=json"
oauth2_redirect_uri = "${WEB_REDIRECT_URI}"
session_secret_key = "${WEB_SESSION_SECRET}"
# "encrypted" rather than config.py's "ephemeral", deliberately: Docker is the
# one shape that provisions the prerequisite itself. entrypoint.sh mints
# /data/.web_token_key and compose hands it to the web service, so post-as-user
# Talk mirroring and read sync work out of the box. Ansible leaves that key to
# the operator, so every other shape defaults to storing no OAuth pair at rest.
token_storage = "${ISTOTA_WEB_TOKEN_STORAGE:-encrypted}"

[web.map]
provider = "${ISTOTA_WEB_MAP_PROVIDER:-openfreemap}"
api_key = "${ISTOTA_WEB_MAP_API_KEY:-}"
dark_style = "${ISTOTA_WEB_MAP_DARK_STYLE:-}"
light_style = "${ISTOTA_WEB_MAP_LIGHT_STYLE:-}"
attribution = "${ISTOTA_WEB_MAP_ATTRIBUTION:-}"

[web.chat]
talk_read_sync_interval = ${ISTOTA_WEB_CHAT_TALK_READ_SYNC_INTERVAL:-60}

[site]
hostname = "${WEB_SITE_HOSTNAME}"
TOML
        echo "[istota] Web UI configured (OAuth2 client=${OAUTH_CLIENT_ID})"
    fi

    # Primary user
    cat >> "$CONFIG_FILE" <<TOML

[users.${USER_NAME}]
display_name = "${DISPLAY_NAME}"
timezone = "${TIMEZONE}"
TOML

    if [ -n "${USER_EMAIL:-}" ]; then
        echo "email_addresses = [\"${USER_EMAIL}\"]" >> "$CONFIG_FILE"
    fi
    # log_channel: explicit env var overrides auto-provisioned token
    EFFECTIVE_LOG_CHANNEL="${USER_LOG_CHANNEL:-${LOG_TOKEN:-}}"
    if [ -n "$EFFECTIVE_LOG_CHANNEL" ]; then
        echo "log_channel = \"${EFFECTIVE_LOG_CHANNEL}\"" >> "$CONFIG_FILE"
    fi
    # alerts_channel: explicit env var overrides auto-provisioned token
    EFFECTIVE_ALERTS_CHANNEL="${USER_ALERTS_CHANNEL:-${ALERTS_TOKEN:-}}"
    if [ -n "$EFFECTIVE_ALERTS_CHANNEL" ]; then
        echo "alerts_channel = \"${EFFECTIVE_ALERTS_CHANNEL}\"" >> "$CONFIG_FILE"
    fi
    if [ -n "${USER_MAX_FOREGROUND_WORKERS:-}" ]; then
        echo "max_foreground_workers = ${USER_MAX_FOREGROUND_WORKERS}" >> "$CONFIG_FILE"
    fi
    if [ -n "${USER_MAX_BACKGROUND_WORKERS:-}" ]; then
        echo "max_background_workers = ${USER_MAX_BACKGROUND_WORKERS}" >> "$CONFIG_FILE"
    fi
    _skills_list="$(toml_string_list "${USER_DISABLED_SKILLS:-}")"
    if [ -n "$_skills_list" ]; then
        echo "disabled_skills = $_skills_list" >> "$CONFIG_FILE"
    fi
    # Modules the user has switched off. Separate axis from the module
    # *_ENABLED variables above: those decide whether the deployment carries
    # the module at all (and, for feeds and money, whether a [[users.X.resources]]
    # block is written); this one is the per-user opt-out `modules.py` reads,
    # and it is the only route to health and briefings, which have no
    # deployment-level toggle.
    _modules_list="$(toml_string_list "${USER_DISABLED_MODULES:-}")"
    if [ -n "$_modules_list" ]; then
        echo "disabled_modules = $_modules_list" >> "$CONFIG_FILE"
    fi

    # --- Module resources ---
    # Append [[users.X.resources]] entries for opt-in modules. Resource
    # blocks must come after all scalar [users.X] keys (TOML rule: subtable
    # arrays close the parent table). Workspace dirs and starter files are
    # seeded outside this block (after the if/else) so toggling a module on
    # later still gets the workspace, even if config.toml already exists.

    if [ "${ISTOTA_FEEDS_ENABLED:-false}" = "true" ]; then
        cat >> "$CONFIG_FILE" <<TOML

[[users.${USER_NAME}.resources]]
type = "feeds"
name = "Feeds"
TOML
    fi

    if [ "${ISTOTA_LOCATION_ENABLED:-false}" = "true" ] && [ -n "${LOCATION_INGEST_TOKEN:-}" ]; then
        cat >> "$CONFIG_FILE" <<TOML

[[users.${USER_NAME}.resources]]
type = "overland"
name = "Location"
ingest_token = "${LOCATION_INGEST_TOKEN}"
TOML
    fi

    if [ "${ISTOTA_MONEY_ENABLED:-false}" = "true" ]; then
        cat >> "$CONFIG_FILE" <<TOML

[[users.${USER_NAME}.resources]]
type = "money"
name = "Money"
TOML
        # Escape into a TOML basic string (backslash + double-quote only;
        # control chars are unlikely in passwords but get caught by Python's
        # repr fallback). Plain shell interpolation would let a `"` in the
        # password break the TOML.
        if [ -n "${MONARCH_EMAIL:-}" ]; then
            python3 - "${MONARCH_EMAIL}" "${MONARCH_PASSWORD:-}" >> "$CONFIG_FILE" <<'PY'
import sys
def toml_str(v: str) -> str:
    return '"' + v.replace("\\", "\\\\").replace('"', '\\"') + '"'
print(f"monarch_email = {toml_str(sys.argv[1])}")
print(f"monarch_password = {toml_str(sys.argv[2])}")
PY
        fi
    fi

}

# Render to a sibling and move it into place, so a partial file can never be
# mistaken for a finished one.
#
# The preflight above covers four inputs; everything else that can fail does so
# *after* the first `cat >` has already truncated the destination — python3
# missing, ENOSPC, a future unguarded `${VAR}` read. Writing in place would put
# a truncated config where a working one was, and the daemon would exec on the
# fragment.
#
# Since ISSUE-368 this is also what makes a failed render *survivable*: the
# entrypoint renders on every boot, and its fallback — keep the existing config,
# say so loudly, re-render next boot — is only safe because a failure here
# cannot have touched the file that fallback returns to.
#
# The sibling rather than mktemp: `mv` is only atomic within a filesystem, and
# /tmp is a different one in most of these deployments.
config_final="$CONFIG_FILE"
config_partial="${config_final}.partial"
trap 'rm -f "$config_partial"' EXIT
CONFIG_FILE="$config_partial"

render_config

mv -f "$config_partial" "$config_final"
trap - EXIT

# Moved out of the body so it says what it means: the file is in place by the
# time this prints, which was not true when it sat at the end of the render.
echo "[istota] Config written to ${config_final}"
