"""Every file under ``docker/devbox/lib/`` is pinned to something in ``src/``.

Docker cannot ``COPY`` from outside its build context and the devbox context is
``docker/devbox/``, so the image's Python leaves live there as second copies.
Three files do today, and they are pinned two different ways:

* ``istota_forge_cli.py`` and ``istota_devbox_exec_protocol.py`` are **byte
  copies**, generated by ``scripts/sync-devbox-lib.sh`` and pinned by a byte
  comparison in ``test_forge_cli.py`` and ``test_devbox_exec_protocol.py``.
* ``istota_devbox_client.py`` is **not a copy of anything**. It is a rewrite of
  the client half of ``devbox_proxy_protocol`` for a shim that has no istota
  package on its path, and it carries `call`, `die` and the two exception
  classes that file has no reason to hold. Putting it in ``sync_pairs`` would
  overwrite it with ``devbox_proxy_protocol.py`` and break
  ``git-credential-istota``'s import at image build. So it is pinned
  **behaviourally** instead — the two ``request_line`` / ``encode_request``
  implementations must produce identical bytes for the same input — which is
  the pin F35 asked for and the one the spec's interfaces section describes.

The point of this file is the *third* assertion, not either of those two. Both
existing guards name their file by hand, so a fourth vendored leaf added later
would be unguarded while they reported green — the failure round 1 shipped
twice. ``test_every_vendored_file_is_pinned`` derives the list by listing the
directory, so a new file there is red until somebody classifies it.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from istota import devbox_proxy_protocol

REPO = Path(__file__).resolve().parents[1]
LIB_DIR = REPO / "docker" / "devbox" / "lib"
SYNC_SCRIPT = REPO / "scripts" / "sync-devbox-lib.sh"

#: Vendored files that are *not* byte copies, mapped to the class in this module
#: that pins each one. The value is checked: an entry naming a class that does
#: not exist is red, so silencing a file by adding a dict line is not a thing
#: this map lets you do. That mattered — the first draft carried a prose reason
#: instead, with a comment admitting membership was unenforced, which is the
#: same shape as the two per-file guards this module was written to replace.
_BEHAVIOURAL_PINS = {
    "istota_devbox_client.py": "TestTheCredentialClientWireFormat",
}


def _sync_pairs() -> list[tuple[str, str]]:
    """``(repo-relative source, destination basename)`` for every byte copy.

    Parsed out of the script rather than restated, so the two cannot disagree
    about which files the sync covers. The split is `rsplit`, matching the
    script's own `${pair##*:}` — `split` would disagree with it about a source
    path containing a colon, which is contrived but is exactly the kind of
    disagreement a parser written beside a shell script exists to not have.
    """
    inside = False
    pairs: list[tuple[str, str]] = []
    for line in SYNC_SCRIPT.read_text().splitlines():
        stripped = line.strip()
        if stripped.startswith("sync_pairs=("):
            inside = True
            continue
        if inside:
            if stripped.startswith(")"):
                break
            if stripped.startswith('"') and ":" in stripped:
                source, destination = stripped.strip('"').rsplit(":", 1)
                pairs.append((source, destination))
    return pairs


def _sync_pair_destinations() -> set[str]:
    return {destination for _, destination in _sync_pairs()}


def _vendored_files() -> list[str]:
    """Every file in the directory, not every `*.py` file.

    The glob was `*.py`, which reopened the hole this module closes one level
    down: `docker/devbox/Dockerfile` can COPY a policy JSON, a shell script or a
    data blob out of here just as easily as a module, and none of those would
    have been visible to the coverage guard below.
    """
    return sorted(p.name for p in LIB_DIR.iterdir() if p.is_file())


class TestTheDirectoryIsFullyAccountedFor:
    def test_the_sync_script_was_parsed(self):
        """A parser that silently matched nothing would make the guard below
        pass by declaring every file unsynced, then fail it for the wrong
        reason — or, with a different bug, pass it vacuously. Assert the parse
        first so a shape change in the script reads as a shape change."""
        assert _sync_pair_destinations() == {
            "istota_forge_cli.py",
            "istota_devbox_exec_protocol.py",
        }, (
            "either the parser stopped matching, or a sync pair was added or "
            "removed and this set needs the same edit"
        )

    def test_every_sync_pair_is_actually_in_sync(self):
        """The byte comparison, here, over the parsed pairs.

        `test_every_vendored_file_is_pinned` below treats membership of
        `sync_pairs` as pinned, and membership alone only means the *script*
        would copy the file. The two byte comparisons in the tree live in
        `test_forge_cli.py` and `test_devbox_exec_protocol.py` and each names
        one file by hand, so a third pair added to the script and never synced
        would be reported pinned by a test that compared nothing. Doing it over
        the parsed pairs closes that, and makes the two per-file tests
        redundant rather than load-bearing.
        """
        for source, destination in _sync_pairs():
            canonical = REPO / source
            vendored = LIB_DIR / destination
            assert canonical.exists(), f"{source} does not exist"
            assert vendored.exists(), (
                f"docker/devbox/lib/{destination} missing — "
                "run scripts/sync-devbox-lib.sh"
            )
            assert canonical.read_bytes() == vendored.read_bytes(), (
                f"{source} and docker/devbox/lib/{destination} have drifted — "
                "run scripts/sync-devbox-lib.sh"
            )

    def test_every_behavioural_pin_names_a_class_that_exists(self):
        """An entry in `_BEHAVIOURAL_PINS` is a claim that a test holds the
        file. Unchecked, the map is a way to silence the coverage guard with a
        one-line dict entry — the failure this module exists to close, moved up
        one level. Checked, adding an entry costs writing the test."""
        for name, class_name in _BEHAVIOURAL_PINS.items():
            assert class_name in globals(), (
                f"_BEHAVIOURAL_PINS claims {name} is pinned by {class_name}, "
                "which is not defined in this module"
            )

    def test_every_vendored_file_is_pinned(self):
        """The list comes from the directory, not from this file.

        Both existing drift guards name one file each, so nothing in the tree
        noticed that `istota_devbox_client.py` was pinned by nothing at all —
        no byte comparison, no behavioural test, and not in `sync_pairs`. A
        fourth leaf added under `docker/devbox/lib/` would have been the same
        story. It is red here until it is either synced or listed above with a
        test behind it.

        The listing is `iterdir`, not `glob("*.py")`: the Dockerfile can COPY a
        non-Python file out of this directory too, and a guard that only sees
        modules is the same blind spot one file type over.
        """
        synced = _sync_pair_destinations()
        unpinned = [
            name
            for name in _vendored_files()
            if name not in synced and name not in _BEHAVIOURAL_PINS
        ]
        assert unpinned == [], (
            f"{unpinned} under docker/devbox/lib/ is pinned by nothing. Either "
            "add it to sync_pairs in scripts/sync-devbox-lib.sh as a byte copy, "
            "or add it to _BEHAVIOURAL_PINS here with a test that holds it to "
            "its src/ counterpart."
        )

    def test_a_behavioural_pin_is_not_also_a_sync_pair(self):
        """The two are alternatives. A file in both would be byte-copied over
        the rewrite the behavioural pin exists to protect."""
        overlap = set(_BEHAVIOURAL_PINS) & _sync_pair_destinations()
        assert overlap == set(), overlap

    def test_no_vendored_file_is_a_symlink(self):
        """A symlink passes every byte comparison and fails `docker build` with
        "COPY failed: … outside the build context"."""
        for name in _vendored_files():
            assert not (LIB_DIR / name).is_symlink(), name


class TestTheCredentialClientWireFormat:
    """`istota_devbox_client.request_line` against
    `devbox_proxy_protocol.encode_request`.

    The daemon parses what the shim writes. The two implementations disagreeing
    is a wire-format disagreement between the two ends of the credential
    socket, which is the failure mode with no error message — the same argument
    `test_devbox_exec_protocol.py` makes for its byte comparison. Bytes rather
    than a hash, because this file is deliberately not a copy: `encode_request`
    returns `str` and `request_line` returns UTF-8 `bytes`, and the separator
    and key ordering are the part that has to agree.
    """

    @staticmethod
    def _client():
        import importlib.util

        path = LIB_DIR / "istota_devbox_client.py"
        spec = importlib.util.spec_from_file_location("istota_devbox_client", path)
        assert spec and spec.loader
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        return module

    @pytest.mark.parametrize(
        "action,fields",
        [
            ("ping", {}),
            ("git_credential", {"op": "get", "host": "gitlab.com"}),
            ("forge_token", {"provider": "gitlab"}),
            # Separator agreement: a space after the comma or the colon would
            # still parse, and would still be a different byte string, which is
            # what a hash-equality pin could not have expressed here.
            ("git_credential", {"op": "get", "host": "a b", "protocol": "https"}),
            # Non-ASCII and a key ordering that is not sorted: `json.dumps`
            # preserves insertion order, so the two must build the payload the
            # same way round, not merely carry the same pairs.
            ("forge_token", {"z": "ünïcode", "a": 1, "m": None}),
        ],
    )
    def test_the_two_implementations_produce_identical_bytes(self, action, fields):
        client = self._client()
        canonical = devbox_proxy_protocol.encode_request(action, **fields)
        assert client.request_line(action, **fields) == canonical.encode("utf-8")

    def test_the_line_is_newline_terminated_and_holds_no_other_newline(self):
        """The daemon reads one line per connection, so a payload that split
        across two would be read as a request plus a malformed second one."""
        client = self._client()
        line = client.request_line("git_credential", op="get", host="gitlab.com")
        assert line.endswith(b"\n")
        assert line.count(b"\n") == 1

    def test_the_client_imports_nothing_from_istota(self):
        """It is imported by a process in a container with no such package.

        Parsed rather than grepped. The substring form this replaced tested for
        a leading newline, so it missed an import on line 1 and every indented
        one — and a function-local import is the idiom this codebase reaches
        for whenever a module-scope one would cost a cycle or an import graph,
        so it is the shape the regression would actually take.
        """
        import ast

        tree = ast.parse((LIB_DIR / "istota_devbox_client.py").read_text())
        reached = set()
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                reached.update(alias.name for alias in node.names)
            elif isinstance(node, ast.ImportFrom) and node.module:
                reached.add(node.module)
        offenders = [
            name
            for name in reached
            if name == "istota" or name.startswith("istota.")
        ]
        assert offenders == [], (
            f"{offenders} is imported by a file that runs in a container with "
            "no istota package on its path"
        )
